env:
  CI_ALLOW_ROOT: '1'
  CI_CLOSE_STDIN: '1'
  CI_CONFIG: ./examples/ci.nix
  CI_PLATFORM: gh-actions
jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
    - id: crex
      run: crex --help | lolcat
  ci-check:
    name: example check
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@modules
    - id: ci-action-build
      name: nix build ci.gh-actions.configFile
      uses: arcnmx/ci/actions/nix/build@modules
      with:
        attrs: ci.gh-actions.configFile
        out-link: .ci/workflow.yml
    - id: ci-action-compare
      name: gh-actions compare
      uses: arcnmx/ci/actions/nix/run@modules
      with:
        args: -u .github/workflows/example.yml .ci/workflow.yml
        attrs: nixpkgs.diffutils
        command: diff
  docs:
    env:
      GITHUB_EVENT_NAME: ${{ github.event_name }}
      GITHUB_REF: ${{ github.ref }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_SHA: ${{ github.sha }}
      GIT_DEPLOY_KEY: ${{ secrets.deploy_key }}
    name: docs
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@modules
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-test
      name: nix test
      uses: arcnmx/ci/actions/nix/run@modules
      with:
        attrs: ci.stage.docs.run.test
        quiet: false
  mac:
    name: example-mac
    runs-on: macOS-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@modules
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@modules
      with:
        attrs: ci.job.mac.run.bootstrap
        quiet: false
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-test
      name: nix test
      uses: arcnmx/ci/actions/nix/run@modules
      with:
        attrs: ci.job.mac.run.test
        quiet: false
  old:
    name: example-old
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@modules
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@modules
      with:
        attrs: ci.job.old.run.bootstrap
        quiet: false
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-test
      name: nix test
      uses: arcnmx/ci/actions/nix/run@modules
      with:
        attrs: ci.job.old.run.test
        quiet: false
  script:
    name: example script
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@modules
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-test
      name: nix test
      uses: arcnmx/ci/actions/nix/run@modules
      with:
        attrs: ci.stage.script.run.test
        quiet: false
    - uses: actions/checkout@v1
    - name: example.sh
      run: ./example.sh
      working-directory: examples
name: example
'on':
- push
- pull_request
