jobs:
  ci:
    env:
      CI_ALLOW_ROOT: '1'
      CI_CLOSE_STDIN: '1'
      CI_PLATFORM: gh-actions
    name: example
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@modules
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@modules
      with:
        attrs: ci.run.bootstrap
        options: --arg config ./examples/ci.nix
        quiet: false
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-test
      name: nix test
      uses: arcnmx/ci/actions/nix/run@modules
      with:
        attrs: ci.run.test
        options: --arg config ./examples/ci.nix
        quiet: false
    - id: crex
      run: crex --help | lolcat
  ci-check:
    env:
      CI_ALLOW_ROOT: '1'
      CI_CLOSE_STDIN: '1'
      CI_PLATFORM: gh-actions
    name: example check
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@modules
    - id: ci-action-build
      name: nix build ci.gh-actions.configFile
      uses: arcnmx/ci/actions/nix/build@modules
      with:
        attrs: ci.gh-actions.configFile
        options: --arg config ./examples/ci.nix
        out-link: .ci/workflow.yml
    - id: ci-action-compare
      name: gh-actions compare
      uses: arcnmx/ci/actions/nix/run@modules
      with:
        args: -u .github/workflows/example.yml .ci/workflow.yml
        attrs: nixpkgs.diffutils
        command: diff
  script:
    name: example script
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: example.sh
      run: ./example.sh
      working-directory: examples
name: example
'on':
- push
- pull_request
