jobs:
  ci:
    env:
      CI_ALLOW_ROOT: '1'
      CI_CLOSE_STDIN: '1'
      CI_PLATFORM: gh-actions
    name: tests-impure
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: ./actions/nix/install
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-setup
      name: nix setup
      uses: ./actions/nix/run
      with:
        attrs: ci.run.setup
        options: --arg config ./tests/impure.nix
        quiet: false
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-test
      name: nix test
      uses: ./actions/nix/run
      with:
        attrs: ci.run.test
        options: --arg config ./tests/impure.nix
        quiet: false
  ci-check:
    env:
      CI_ALLOW_ROOT: '1'
      CI_CLOSE_STDIN: '1'
      CI_PLATFORM: gh-actions
    name: tests-impure check
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: ./actions/nix/install
    - id: ci-action-build
      name: nix build ci.gh-actions.configFile
      uses: ./actions/nix/build
      with:
        attrs: ci.gh-actions.configFile
        options: --arg config ./tests/impure.nix
        out-link: .ci/workflow.yml
    - id: ci-action-compare
      name: gh-actions compare
      uses: ./actions/nix/run
      with:
        args: -u .github/workflows/tests-impure.yml .ci/workflow.yml
        attrs: nixpkgs.diffutils
        command: diff
name: tests-impure
'on':
- push
- pull_request
